version: 2
jobs:
  build:
    machine: true   
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run app
          command: |
            . venv/bin/activate
            python src/app.py &
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest
      - run:
          name: docker build image
          command: |      
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t victormcl/apptest:latest .
      - run:
          name: docker push image
          command: | 
            docker push victormcl/apptest:latest      
      - run:
          name: docker rm image
          command: |            
            docker rmi victormcl/apptest:latest     
